plugins {
    id 'application'
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    // Selenium WebDriver
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'

    // JUnit 5 (Jupiter)
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'

    // WebDriverManager untuk otomatisasi download WebDriver
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'

    testImplementation 'io.rest-assured:rest-assured:5.4.0'

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // Jika menggunakan Java 21
    }
}

// Main class untuk aplikasi Java (boleh dihapus jika tidak digunakan)
application {
    mainClass = 'org.example.App' // Hapus jika tidak ada aplikasi utama
}

// Gunakan JUnit Platform untuk menjalankan test
tasks.named('test') {
    useJUnitPlatform()

    // Tambahkan pengaturan output untuk test
    testLogging {
        events "passed", "failed", "skipped", "standard_out", "standard_error"
        showStandardStreams = true
    }
}
